packages:
  - packages/*

catalogs:
  build:
    bumpp: ^10.3.2
    tsdown: ^0.17.3
  eslint:
    '@antfu/eslint-config': ^6.6.1
    eslint: ^9.39.1
  testing:
    vitest: ^4.0.15
  types:
    '@types/node': ^25.0.1
  typescript:
    typescript: ^5.9.3
  utils:
    ajv: ^8.17.1
    ajv-formats: ^3.0.1
    ansis: ^4.2.0
    cac: ^6.7.14
    esno: '*'
    execa: ^9.6.1
    lint-staged: ^16.2.7
    restore-cursor: ^5.1.0
    simple-git-hooks: ^2.13.1
    terminal-link: ^5.0.0
    tinyglobby: ^0.2.15
    zod: ^4.1.13

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
