packages:
  - packages/*

catalogs:
  build:
    bumpp: ^10.3.1
    tsdown: ^0.15.9
  eslint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.38.0
  testing:
    vitest: ^4.0.2
  types:
    '@types/node': ^24.9.1
  typescript:
    typescript: ^5.9.3
  utils:
    ajv: ^8.17.1
    ajv-formats: ^3.0.1
    ansis: ^4.1.0
    cac: ^6.7.14
    esno: '*'
    execa: ^9.6.0
    lint-staged: ^16.2.6
    restore-cursor: ^5.1.0
    simple-git-hooks: ^2.13.1
    terminal-link: ^4.0.0
    tinyglobby: ^0.2.14
    zod: ^4.1.12

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
